server :
  port : 8080
  servlet:
    encoding:
      force-response: true

spring:
  datasource:
    url: localhost
    username: root
    password: 12345678
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
